/**
 * Monthly building approvals data (ABS Cat. 8731.0)
 * Auto-generated by scripts/refresh-data.mjs — do not edit manually.
 * Last refreshed: 2026-05-29
 * Source: ABS Building Approvals, Table 8731009 (Australia total, all sectors)
 */

export interface BuildingApprovalsRecord {
  date: string
  total_aus: number
  houses_aus: number
  other_aus: number
}

export const BUILDING_APPROVALS: BuildingApprovalsRecord[] = [
  { date: "2021-04-01", total_aus: 21179, houses_aus: 13882, other_aus: 7297 },
  { date: "2021-05-01", total_aus: 21227, houses_aus: 14003, other_aus: 7224 },
  { date: "2021-06-01", total_aus: 20191, houses_aus: 13406, other_aus: 6785 },
  { date: "2021-07-01", total_aus: 19426, houses_aus: 12816, other_aus: 6610 },
  { date: "2021-08-01", total_aus: 19498, houses_aus: 12570, other_aus: 6928 },
  { date: "2021-09-01", total_aus: 19584, houses_aus: 11192, other_aus: 8392 },
  { date: "2021-10-01", total_aus: 16358, houses_aus: 10852, other_aus: 5506 },
  { date: "2021-11-01", total_aus: 17490, houses_aus: 11511, other_aus: 5979 },
  { date: "2021-12-01", total_aus: 16318, houses_aus: 9254, other_aus: 7064 },
  { date: "2022-01-01", total_aus: 10196, houses_aus: 6535, other_aus: 3661 },
  { date: "2022-02-01", total_aus: 18070, houses_aus: 9928, other_aus: 8142 },
  { date: "2022-03-01", total_aus: 16481, houses_aus: 11115, other_aus: 5366 },
  { date: "2022-04-01", total_aus: 14680, houses_aus: 8644, other_aus: 6036 },
  { date: "2022-05-01", total_aus: 17284, houses_aus: 10201, other_aus: 7083 },
  { date: "2022-06-01", total_aus: 16865, houses_aus: 10182, other_aus: 6683 },
  { date: "2022-07-01", total_aus: 14414, houses_aus: 9981, other_aus: 4433 },
  { date: "2022-08-01", total_aus: 18433, houses_aus: 11087, other_aus: 7346 },
  { date: "2022-09-01", total_aus: 17502, houses_aus: 9775, other_aus: 7727 },
  { date: "2022-10-01", total_aus: 15424, houses_aus: 9531, other_aus: 5893 },
  { date: "2022-11-01", total_aus: 16470, houses_aus: 10214, other_aus: 6256 },
  { date: "2022-12-01", total_aus: 15845, houses_aus: 7739, other_aus: 8106 },
  { date: "2023-01-01", total_aus: 9805, houses_aus: 5985, other_aus: 3820 },
  { date: "2023-02-01", total_aus: 13232, houses_aus: 8750, other_aus: 4482 },
  { date: "2023-03-01", total_aus: 14534, houses_aus: 9584, other_aus: 4950 },
  { date: "2023-04-01", total_aus: 11610, houses_aus: 7021, other_aus: 4589 },
  { date: "2023-05-01", total_aus: 16786, houses_aus: 9021, other_aus: 7765 },
  { date: "2023-06-01", total_aus: 13902, houses_aus: 8553, other_aus: 5349 },
  { date: "2023-07-01", total_aus: 12938, houses_aus: 8263, other_aus: 4675 },
  { date: "2023-08-01", total_aus: 14530, houses_aus: 9736, other_aus: 4794 },
  { date: "2023-09-01", total_aus: 13967, houses_aus: 8659, other_aus: 5308 },
  { date: "2023-10-01", total_aus: 15130, houses_aus: 9468, other_aus: 5662 },
  { date: "2023-11-01", total_aus: 15825, houses_aus: 9688, other_aus: 6137 },
  { date: "2023-12-01", total_aus: 12073, houses_aus: 7634, other_aus: 4439 },
  { date: "2024-01-01", total_aus: 11055, houses_aus: 6200, other_aus: 4855 },
  { date: "2024-02-01", total_aus: 13432, houses_aus: 9088, other_aus: 4344 },
  { date: "2024-03-01", total_aus: 13059, houses_aus: 9096, other_aus: 3963 },
  { date: "2024-04-01", total_aus: 13630, houses_aus: 8793, other_aus: 4837 },
  { date: "2024-05-01", total_aus: 15949, houses_aus: 10125, other_aus: 5824 },
  { date: "2024-06-01", total_aus: 12661, houses_aus: 9006, other_aus: 3655 },
  { date: "2024-07-01", total_aus: 16590, houses_aus: 10520, other_aus: 6070 },
  { date: "2024-08-01", total_aus: 14858, houses_aus: 10224, other_aus: 4634 },
  { date: "2024-09-01", total_aus: 14932, houses_aus: 9760, other_aus: 5172 },
  { date: "2024-10-01", total_aus: 17931, houses_aus: 10471, other_aus: 7460 },
  { date: "2024-11-01", total_aus: 15916, houses_aus: 10105, other_aus: 5811 },
  { date: "2024-12-01", total_aus: 14321, houses_aus: 7830, other_aus: 6491 },
  { date: "2025-01-01", total_aus: 13272, houses_aus: 6757, other_aus: 6515 },
  { date: "2025-02-01", total_aus: 16257, houses_aus: 9395, other_aus: 6862 },
  { date: "2025-03-01", total_aus: 15735, houses_aus: 9483, other_aus: 6252 },
  { date: "2025-04-01", total_aus: 14592, houses_aus: 8765, other_aus: 5827 },
  { date: "2025-05-01", total_aus: 16759, houses_aus: 9994, other_aus: 6765 },
  { date: "2025-06-01", total_aus: 16499, houses_aus: 9114, other_aus: 7385 },
  { date: "2025-07-01", total_aus: 18095, houses_aus: 10596, other_aus: 7499 },
  { date: "2025-08-01", total_aus: 15311, houses_aus: 9665, other_aus: 5646 },
  { date: "2025-09-01", total_aus: 18512, houses_aus: 10115, other_aus: 8397 },
  { date: "2025-10-01", total_aus: 17421, houses_aus: 10715, other_aus: 6706 },
  { date: "2025-11-01", total_aus: 18541, houses_aus: 9950, other_aus: 8591 },
  { date: "2025-12-01", total_aus: 15139, houses_aus: 8828, other_aus: 6311 },
  { date: "2026-01-01", total_aus: 10637, houses_aus: 7024, other_aus: 3613 },
  { date: "2026-02-01", total_aus: 18685, houses_aus: 10238, other_aus: 8447 },
  { date: "2026-03-01", total_aus: 17780, houses_aus: 10935, other_aus: 6845 },
]

export interface BuildingApprovalsSummary {
  latest_monthly: number
  annual_run_rate: number
  accord_target: number
  gap_to_target: number
  pct_of_target: number
  yoy_change_pct: number
  latest_date: string
}

export function getBuildingApprovalsSummary(): BuildingApprovalsSummary {
  const latest = BUILDING_APPROVALS[BUILDING_APPROVALS.length - 1]
  // 3-month average × 12 — standard ABS methodology, smooths monthly volatility
  const last3 = BUILDING_APPROVALS.slice(-3)
  const avg3m = last3.reduce((sum, r) => sum + r.total_aus, 0) / 3
  const annual_run_rate = Math.round(avg3m * 12)
  const accord_target = 240000
  const gap_to_target = accord_target - annual_run_rate
  const pct_of_target = Math.round((annual_run_rate / accord_target) * 100)

  // YoY: compare latest month to same month last year (12 records back)
  const twelveMonthsAgo = BUILDING_APPROVALS[BUILDING_APPROVALS.length - 13]
  const yoy_change_pct =
    Math.round(
      ((latest.total_aus - twelveMonthsAgo.total_aus) / twelveMonthsAgo.total_aus) *
        100 *
        10
    ) / 10

  return {
    latest_monthly: latest.total_aus,
    annual_run_rate,
    accord_target,
    gap_to_target,
    pct_of_target,
    yoy_change_pct,
    latest_date: latest.date,
  }
}
