/**
 * Monthly building approvals data (ABS Cat. 8731.0)
 * Auto-generated by scripts/refresh-data.mjs — do not edit manually.
 * Last refreshed: 2026-06-15
 *
 * ── Data source ──────────────────────────────────────────────────────────────
 * Australian Bureau of Statistics — Building Approvals, Australia (Cat. 8731.0)
 * Table 8731009: Total dwellings approved, all sectors, by state and Australia.
 * Released monthly (~12th–15th of the following month).
 * https://www.abs.gov.au/statistics/industry/building-and-construction/building-approvals-australia
 *
 * ── Methodology ──────────────────────────────────────────────────────────────
 * Annual run rate  = trailing 12-month sum of total dwellings approved nationally.
 *                    This is the ABS standard for reporting annual totals and is
 *                    more stable than a short-window annualised rate — seasonal
 *                    outliers (e.g. low January figures) are absorbed across 12
 *                    data points rather than amplified.
 *
 * Supply gap       = National Housing Accord target (240,000/yr) minus annual run rate.
 *                    The Accord (September 2022) committed the Commonwealth, states,
 *                    territories and local government to 1.2 million new homes by 2029.
 *
 * % of target      = annual run rate ÷ 240,000 × 100.
 *
 * YoY change       = latest month's approvals compared to the same calendar month
 *                    in the prior year, expressed as a percentage.
 *
 * ── Coverage ─────────────────────────────────────────────────────────────────
 * Total dwellings = separate houses + other residential (semi-detached, row/terrace,
 * townhouses, flats, apartments). All sectors (private + public).
 * Australia total only — state breakdown in lib/data/state-analysis.ts.
 */

export interface BuildingApprovalsRecord {
  date: string
  total_aus: number
  houses_aus: number
  other_aus: number
}

export const BUILDING_APPROVALS: BuildingApprovalsRecord[] = [
  { date: "2021-05-01", total_aus: 21227, houses_aus: 14003, other_aus: 7224 },
  { date: "2021-06-01", total_aus: 20191, houses_aus: 13406, other_aus: 6785 },
  { date: "2021-07-01", total_aus: 19426, houses_aus: 12816, other_aus: 6610 },
  { date: "2021-08-01", total_aus: 19498, houses_aus: 12570, other_aus: 6928 },
  { date: "2021-09-01", total_aus: 19584, houses_aus: 11192, other_aus: 8392 },
  { date: "2021-10-01", total_aus: 16358, houses_aus: 10852, other_aus: 5506 },
  { date: "2021-11-01", total_aus: 17490, houses_aus: 11511, other_aus: 5979 },
  { date: "2021-12-01", total_aus: 16318, houses_aus: 9254, other_aus: 7064 },
  { date: "2022-01-01", total_aus: 10196, houses_aus: 6535, other_aus: 3661 },
  { date: "2022-02-01", total_aus: 18070, houses_aus: 9928, other_aus: 8142 },
  { date: "2022-03-01", total_aus: 16481, houses_aus: 11115, other_aus: 5366 },
  { date: "2022-04-01", total_aus: 14680, houses_aus: 8644, other_aus: 6036 },
  { date: "2022-05-01", total_aus: 17284, houses_aus: 10201, other_aus: 7083 },
  { date: "2022-06-01", total_aus: 16865, houses_aus: 10182, other_aus: 6683 },
  { date: "2022-07-01", total_aus: 14414, houses_aus: 9981, other_aus: 4433 },
  { date: "2022-08-01", total_aus: 18433, houses_aus: 11087, other_aus: 7346 },
  { date: "2022-09-01", total_aus: 17502, houses_aus: 9775, other_aus: 7727 },
  { date: "2022-10-01", total_aus: 15424, houses_aus: 9531, other_aus: 5893 },
  { date: "2022-11-01", total_aus: 16470, houses_aus: 10214, other_aus: 6256 },
  { date: "2022-12-01", total_aus: 15845, houses_aus: 7739, other_aus: 8106 },
  { date: "2023-01-01", total_aus: 9805, houses_aus: 5985, other_aus: 3820 },
  { date: "2023-02-01", total_aus: 13232, houses_aus: 8750, other_aus: 4482 },
  { date: "2023-03-01", total_aus: 14534, houses_aus: 9584, other_aus: 4950 },
  { date: "2023-04-01", total_aus: 11610, houses_aus: 7021, other_aus: 4589 },
  { date: "2023-05-01", total_aus: 16786, houses_aus: 9021, other_aus: 7765 },
  { date: "2023-06-01", total_aus: 13902, houses_aus: 8553, other_aus: 5349 },
  { date: "2023-07-01", total_aus: 12938, houses_aus: 8263, other_aus: 4675 },
  { date: "2023-08-01", total_aus: 14530, houses_aus: 9736, other_aus: 4794 },
  { date: "2023-09-01", total_aus: 13967, houses_aus: 8659, other_aus: 5308 },
  { date: "2023-10-01", total_aus: 15130, houses_aus: 9468, other_aus: 5662 },
  { date: "2023-11-01", total_aus: 15825, houses_aus: 9688, other_aus: 6137 },
  { date: "2023-12-01", total_aus: 12073, houses_aus: 7634, other_aus: 4439 },
  { date: "2024-01-01", total_aus: 11055, houses_aus: 6200, other_aus: 4855 },
  { date: "2024-02-01", total_aus: 13432, houses_aus: 9088, other_aus: 4344 },
  { date: "2024-03-01", total_aus: 13059, houses_aus: 9096, other_aus: 3963 },
  { date: "2024-04-01", total_aus: 13630, houses_aus: 8793, other_aus: 4837 },
  { date: "2024-05-01", total_aus: 15949, houses_aus: 10125, other_aus: 5824 },
  { date: "2024-06-01", total_aus: 12661, houses_aus: 9006, other_aus: 3655 },
  { date: "2024-07-01", total_aus: 16595, houses_aus: 10529, other_aus: 6066 },
  { date: "2024-08-01", total_aus: 14865, houses_aus: 10209, other_aus: 4656 },
  { date: "2024-09-01", total_aus: 14934, houses_aus: 9761, other_aus: 5173 },
  { date: "2024-10-01", total_aus: 17939, houses_aus: 10476, other_aus: 7463 },
  { date: "2024-11-01", total_aus: 15920, houses_aus: 10109, other_aus: 5811 },
  { date: "2024-12-01", total_aus: 14325, houses_aus: 7834, other_aus: 6491 },
  { date: "2025-01-01", total_aus: 13317, houses_aus: 6758, other_aus: 6559 },
  { date: "2025-02-01", total_aus: 16260, houses_aus: 9398, other_aus: 6862 },
  { date: "2025-03-01", total_aus: 15738, houses_aus: 9488, other_aus: 6250 },
  { date: "2025-04-01", total_aus: 14671, houses_aus: 8766, other_aus: 5905 },
  { date: "2025-05-01", total_aus: 16772, houses_aus: 9998, other_aus: 6774 },
  { date: "2025-06-01", total_aus: 16498, houses_aus: 9112, other_aus: 7386 },
  { date: "2025-07-01", total_aus: 18228, houses_aus: 10729, other_aus: 7499 },
  { date: "2025-08-01", total_aus: 15313, houses_aus: 9667, other_aus: 5646 },
  { date: "2025-09-01", total_aus: 18541, houses_aus: 10123, other_aus: 8418 },
  { date: "2025-10-01", total_aus: 17521, houses_aus: 10722, other_aus: 6799 },
  { date: "2025-11-01", total_aus: 18558, houses_aus: 9959, other_aus: 8599 },
  { date: "2025-12-01", total_aus: 15151, houses_aus: 8850, other_aus: 6301 },
  { date: "2026-01-01", total_aus: 10630, houses_aus: 7032, other_aus: 3598 },
  { date: "2026-02-01", total_aus: 18766, houses_aus: 10289, other_aus: 8477 },
  { date: "2026-03-01", total_aus: 17921, houses_aus: 11042, other_aus: 6879 },
  { date: "2026-04-01", total_aus: 17349, houses_aus: 10310, other_aus: 7039 },
]

export interface BuildingApprovalsSummary {
  latest_monthly: number
  annual_run_rate: number
  accord_target: number
  gap_to_target: number
  pct_of_target: number
  yoy_change_pct: number
  latest_date: string
}

export function getBuildingApprovalsSummary(): BuildingApprovalsSummary {
  const latest = BUILDING_APPROVALS[BUILDING_APPROVALS.length - 1]

  // Annual run rate — trailing 12-month sum (ABS standard methodology).
  // Sums the most recent 12 months of actual approvals data.
  // This is stable across seasonal variation and directly matches what ABS
  // publishes as the annual total in their headline release.
  const last12 = BUILDING_APPROVALS.slice(-12)
  const annual_run_rate = last12.reduce((sum, r) => sum + r.total_aus, 0)

  const accord_target = 240000

  // Supply gap — how many dwellings per year Australia is short of the Accord target.
  const gap_to_target = accord_target - annual_run_rate

  // % of target — what share of the required 240,000/yr is currently being delivered.
  const pct_of_target = Math.round((annual_run_rate / accord_target) * 100)

  // YoY — latest month vs the same calendar month 12 months prior.
  const twelveMonthsAgo = BUILDING_APPROVALS[BUILDING_APPROVALS.length - 13]
  const yoy_change_pct =
    Math.round(
      ((latest.total_aus - twelveMonthsAgo.total_aus) / twelveMonthsAgo.total_aus) *
        100 * 10
    ) / 10

  return {
    latest_monthly: latest.total_aus,
    annual_run_rate,
    accord_target,
    gap_to_target,
    pct_of_target,
    yoy_change_pct,
    latest_date: latest.date,
  }
}
