"use client"

import { useState } from "react"
import Markdown from "./Markdown"

type Source = {
  index: number
  title: string
  agency: string
  year: string
  url: string
  authors: string
  score: number
}

type SearchResult = {
  answer: string
  sources: Source[]
}

const SUGGESTED = [
  "What does the evidence say about SDA supply gaps in regional Australia?",
  "What are the key barriers to community housing investment in Australia?",
  "How does supported housing affect outcomes for people with disability?",
  "What policy interventions have improved housing affordability?",
]

function formatSearchBrief(query: string, result: SearchResult): string {
  const date = new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" })
  const sources = result.sources.map(s =>
    `[${s.index}] ${s.title} · ${s.agency}${s.year ? ` · ${s.year}` : ""}${s.url ? `\n     ${s.url}` : ""}`
  ).join("\n")

  return [
    "HIVE EVIDENCE BRIEF",
    "─".repeat(60),
    `Question: ${query}`,
    `Date: ${date}`,
    "",
    "EVIDENCE SYNTHESIS",
    "─".repeat(60),
    result.answer,
    "",
    `SOURCES (${result.sources.length})`,
    "─".repeat(60),
    sources,
    "",
    "─".repeat(60),
    "Generated by HIVE — Housing Intelligence & Evidence",
    "AI-synthesised from indexed research. Verify against primary sources before use.",
  ].join("\n")
}

export default function HiveSearch() {
  const [query, setQuery]     = useState("")
  const [loading, setLoading] = useState(false)
  const [result, setResult]   = useState<SearchResult | null>(null)
  const [error, setError]     = useState("")
  const [copied, setCopied]   = useState(false)

  const exportBrief = async () => {
    if (!result) return
    const text = formatSearchBrief(query, result)
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  const search = async (q: string) => {
    if (!q.trim()) return
    setLoading(true)
    setResult(null)
    setError("")
    setQuery(q)

    try {
      const res = await fetch("/api/search", {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({ query: q }),
      })
      const data = await res.json()
      if (data.error) setError(data.error)
      else setResult(data)
    } catch {
      setError("Something went wrong. Please try again.")
    } finally {
      setLoading(false)
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    search(query)
  }

  return (
    <div>

      {/* ── Search bar ───────────────────────────────────── */}
      <form onSubmit={handleSubmit} style={{ marginBottom: 20 }}>
        <div style={{ display: "flex", gap: 10 }}>
          <input
            type="text"
            value={query}
            onChange={e => setQuery(e.target.value)}
            placeholder="What does the research say about..."
            className="hive-input"
            disabled={loading}
            style={{ flex: 1, padding: "11px 16px", fontSize: "0.88rem" }}
          />
          <button
            type="submit"
            disabled={loading || !query.trim()}
            className="hive-btn"
            style={{ padding: "11px 22px", fontSize: "0.82rem", whiteSpace: "nowrap", opacity: loading || !query.trim() ? 0.5 : 1 }}
          >
            {loading ? "Searching…" : "Search →"}
          </button>
        </div>
      </form>

      {/* ── Suggested questions ──────────────────────────── */}
      {!result && !loading && (
        <div>
          <div style={{ fontSize: "0.65rem", fontWeight: 700, color: "#4a5a6a", letterSpacing: "1px", textTransform: "uppercase", marginBottom: 10 }}>
            Try asking
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            {SUGGESTED.map(q => (
              <button
                key={q}
                onClick={() => search(q)}
                style={{
                  width: "100%",
                  textAlign: "left",
                  background: "rgba(255,255,255,0.03)",
                  border: "1px solid #1e2d40",
                  borderRadius: 8,
                  padding: "11px 16px",
                  fontSize: "0.82rem",
                  color: "#8899aa",
                  cursor: "pointer",
                  transition: "all 0.15s",
                }}
                onMouseEnter={e => {
                  (e.currentTarget as HTMLButtonElement).style.color = "#c8d8e8"
                  ;(e.currentTarget as HTMLButtonElement).style.borderColor = "#2a4060"
                  ;(e.currentTarget as HTMLButtonElement).style.background = "rgba(255,255,255,0.06)"
                }}
                onMouseLeave={e => {
                  (e.currentTarget as HTMLButtonElement).style.color = "#8899aa"
                  ;(e.currentTarget as HTMLButtonElement).style.borderColor = "#1e2d40"
                  ;(e.currentTarget as HTMLButtonElement).style.background = "rgba(255,255,255,0.03)"
                }}
              >
                {q}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* ── Loading ──────────────────────────────────────── */}
      {loading && (
        <div style={{ textAlign: "center", padding: "40px 0" }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 12, color: "#8899aa", fontSize: "0.85rem" }}>
            <div style={{
              width: 18, height: 18,
              border: "2px solid rgba(246,201,14,0.2)",
              borderTopColor: "#f6c90e",
              borderRadius: "50%",
              animation: "spin 0.7s linear infinite",
            }} />
            Searching 683 reports and synthesising answer…
          </div>
        </div>
      )}

      {/* ── Error ────────────────────────────────────────── */}
      {error && (
        <div className="hive-card" style={{ border: "1px solid rgba(192,97,74,0.3)", background: "rgba(192,97,74,0.06)", padding: "14px 18px", fontSize: "0.85rem", color: "#c0614a" }}>
          {error}
        </div>
      )}

      {/* ── Results ──────────────────────────────────────── */}
      {result && (
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>

          {/* Back */}
          <button
            onClick={() => { setResult(null); setQuery("") }}
            style={{ background: "none", border: "none", padding: 0, color: "#6b8aa0", fontSize: "0.82rem", cursor: "pointer", textAlign: "left" }}
          >
            ← New search
          </button>

          {/* Question echo */}
          <div className="hive-card" style={{ padding: "12px 16px" }}>
            <div style={{ fontSize: "0.65rem", fontWeight: 700, color: "#4a5a6a", letterSpacing: "1px", textTransform: "uppercase", marginBottom: 6 }}>Your question</div>
            <div style={{ fontSize: "0.88rem", color: "#fff", fontWeight: 600 }}>{query}</div>
          </div>

          {/* Answer */}
          <div className="hive-card" style={{ padding: "20px 22px" }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <span style={{ fontSize: "1.1rem" }}>🐝</span>
                <span style={{ fontSize: "0.65rem", fontWeight: 700, color: "#f6c90e", letterSpacing: "1px", textTransform: "uppercase" }}>
                  HIVE Analysis · {result.sources.length} sources
                </span>
              </div>
              <button
                onClick={exportBrief}
                style={{
                  padding: "5px 14px", fontSize: "0.72rem", fontWeight: 700,
                  color: copied ? "#0b1220" : "#f6c90e",
                  background: copied ? "#f6c90e" : "rgba(246,201,14,0.06)",
                  border: "1px solid rgba(246,201,14,0.3)",
                  borderRadius: 6, cursor: "pointer", transition: "all 0.2s",
                  whiteSpace: "nowrap",
                }}
              >
                {copied ? "✓ Copied to clipboard" : "Export Brief"}
              </button>
            </div>
            <Markdown text={result.answer} />
          </div>

          {/* Sources */}
          {result.sources.length > 0 && (
            <div>
              <div style={{ fontSize: "0.65rem", fontWeight: 700, color: "#4a5a6a", letterSpacing: "1px", textTransform: "uppercase", marginBottom: 10 }}>
                Sources retrieved ({result.sources.length})
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                {result.sources.map(s => (
                  <div key={s.index} id={`hive-source-${s.index}`} className="hive-card" style={{ padding: "12px 16px", display: "flex", gap: 14, scrollMarginTop: 90 }}>
                    <span style={{ color: "#f6c90e", fontWeight: 800, fontSize: "0.78rem", flexShrink: 0, marginTop: 2, minWidth: 24 }}>
                      [{s.index}]
                    </span>
                    <div style={{ minWidth: 0 }}>
                      <div style={{ fontSize: "0.85rem", color: "#fff", fontWeight: 600, lineHeight: 1.4, marginBottom: 4 }}>{s.title}</div>
                      <div style={{ fontSize: "0.72rem", color: "#4a5a6a" }}>
                        {s.agency}{s.year ? ` · ${s.year}` : ""}{s.authors ? ` · ${s.authors}` : ""}
                      </div>
                      {s.url && (
                        <a
                          href={s.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          style={{ fontSize: "0.72rem", color: "#4d7fb5", textDecoration: "none", marginTop: 4, display: "inline-block" }}
                        >
                          View source ↗
                        </a>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Disclaimer */}
          <div style={{ fontSize: "0.7rem", color: "#334455", textAlign: "center", paddingBottom: 8 }}>
            AI-synthesised from indexed research. Verify against primary sources before relying on for decisions.
          </div>
        </div>
      )}

    </div>
  )
}
