// Shared "Export Brief" formatter — turns the markdown answer + sources into a
// clean plain-text version AND a styled HTML version, then either downloads it
// as a Word document, opens a print view for PDF, or copies it to the clipboard.

export type BriefSource = {
  index: number
  title: string
  agency: string
  year: string | number
  url?: string
  authors?: string
  score?: number
}

export type BriefOpts = {
  docTitle: string
  metaLines: string[]
  answer: string
  sources: BriefSource[]
  footer?: string
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

// strip markdown emphasis/links for plain text
function stripInline(s: string): string {
  return s
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 ($2)")
}

// inline markdown -> HTML
function inlineHtml(s: string): string {
  return esc(s)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\[(\d+(?:\s*,\s*\d+)*)\]/g, '<sup style="color:#b8860b;font-weight:700">[$1]</sup>')
}

const isH = (l: string) => /^#{1,4}\s+/.test(l)
const isUl = (l: string) => /^[-*]\s+/.test(l)
const isOl = (l: string) => /^\d+\.\s+/.test(l)

function mdToPlain(md: string): string {
  return (md || "").replace(/\r/g, "").split("\n").map(line => {
    const t = line.trim()
    const h = /^(#{1,4})\s+(.*)$/.exec(t)
    if (h) {
      const lvl = h[1].length
      const txt = stripInline(h[2])
      return lvl === 1 ? txt.toUpperCase() : lvl === 2 ? "\n" + txt.toUpperCase() : "\n" + txt
    }
    if (isUl(t)) return "  • " + stripInline(t.replace(/^[-*]\s+/, ""))
    if (isOl(t)) return "  " + stripInline(t)
    return stripInline(line)
  }).join("\n").replace(/\n{3,}/g, "\n\n").trim()
}

function mdToHtml(md: string): string {
  const lines = (md || "").replace(/\r/g, "").split("\n")
  let html = ""
  let i = 0
  while (i < lines.length) {
    const t = lines[i].trim()
    if (t === "") { i++; continue }
    const h = /^(#{1,4})\s+(.*)$/.exec(t)
    if (h) {
      const lvl = h[1].length
      const style = lvl === 1
        ? "font-size:18px;font-weight:700;margin:6px 0 10px"
        : lvl === 2
          ? "font-size:14px;font-weight:700;text-transform:uppercase;letter-spacing:0.4px;color:#b8860b;margin:16px 0 6px"
          : "font-size:13px;font-weight:700;margin:12px 0 4px"
      html += `<div style="${style}">${inlineHtml(h[2])}</div>`
      i++
      continue
    }
    if (isUl(t)) {
      html += '<ul style="margin:6px 0 10px;padding-left:20px">'
      while (i < lines.length && isUl(lines[i].trim())) {
        html += `<li style="margin-bottom:3px">${inlineHtml(lines[i].trim().replace(/^[-*]\s+/, ""))}</li>`
        i++
      }
      html += "</ul>"
      continue
    }
    if (isOl(t)) {
      html += '<ol style="margin:6px 0 10px;padding-left:22px">'
      while (i < lines.length && isOl(lines[i].trim())) {
        html += `<li style="margin-bottom:3px">${inlineHtml(lines[i].trim().replace(/^\d+\.\s+/, ""))}</li>`
        i++
      }
      html += "</ol>"
      continue
    }
    const para: string[] = []
    while (i < lines.length) {
      const x = lines[i].trim()
      if (x === "" || isH(x) || isUl(x) || isOl(x)) break
      para.push(x)
      i++
    }
    html += `<p style="margin:0 0 11px;line-height:1.6">${inlineHtml(para.join(" "))}</p>`
  }
  return html
}

function defaultFooter(o: BriefOpts): string {
  return o.footer ?? "Generated by HIVE — Housing Intelligence & Evidence. AI-synthesised from indexed research; verify against primary sources before use."
}

function briefPlainText(o: BriefOpts): string {
  const plainSources = o.sources.map(s =>
    `[${s.index}] ${s.title} · ${s.agency}${s.year ? ` · ${s.year}` : ""}${s.url ? `\n     ${s.url}` : ""}`
  ).join("\n")
  return [
    o.docTitle.toUpperCase(),
    "=".repeat(58),
    ...o.metaLines,
    "",
    mdToPlain(o.answer),
    "",
    `SOURCES (${o.sources.length})`,
    "-".repeat(58),
    plainSources,
    "",
    "-".repeat(58),
    defaultFooter(o),
  ].join("\n")
}

function briefHtmlBody(o: BriefOpts): string {
  const htmlSources = o.sources.map(s =>
    `<div style="margin-bottom:5px"><strong style="color:#b8860b">[${s.index}]</strong> ${esc(s.title)} — ${esc(s.agency)}${s.year ? ` · ${esc(String(s.year))}` : ""}${s.url ? ` · <a href="${esc(s.url)}" style="color:#2563eb">source</a>` : ""}</div>`
  ).join("")
  return `<div style="font-family:-apple-system,Segoe UI,Arial,sans-serif;color:#1a1a1a;font-size:13px;max-width:720px">
<div style="font-size:11px;letter-spacing:1.5px;text-transform:uppercase;color:#999;font-weight:700;margin-bottom:6px">${esc(o.docTitle)}</div>
${o.metaLines.map(m => `<div style="font-size:12px;color:#555">${inlineHtml(m)}</div>`).join("")}
<hr style="border:none;border-top:1px solid #e2e2e2;margin:12px 0"/>
${mdToHtml(o.answer)}
<hr style="border:none;border-top:1px solid #e2e2e2;margin:14px 0"/>
<div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.5px;color:#999;margin-bottom:8px">Sources (${o.sources.length})</div>
${htmlSources}
<p style="font-size:11px;color:#aaa;margin-top:16px">${esc(defaultFooter(o))}</p>
</div>`
}

function fileSlug(t: string): string {
  return t.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "hive-brief"
}

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1500)
}

// Download a formatted Word document (.doc) — opens in Word / Pages / Google Docs
export function downloadWordBrief(o: BriefOpts): void {
  const body = briefHtmlBody(o)
  const doc =
    `<!DOCTYPE html><html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>` +
    `<head><meta charset='utf-8'><title>${esc(o.docTitle)}</title></head><body>${body}</body></html>`
  triggerDownload(new Blob(["﻿", doc], { type: "application/msword" }), `${fileSlug(o.docTitle)}.doc`)
}

// Open a clean print view — the browser's print dialog lets the user "Save as PDF"
export function printPdfBrief(o: BriefOpts): void {
  const body = briefHtmlBody(o)
  const w = window.open("", "_blank")
  if (!w) { downloadWordBrief(o); return } // popup blocked → fall back to a Word download
  w.document.write(
    `<!DOCTYPE html><html><head><meta charset='utf-8'><title>${esc(o.docTitle)}</title>` +
    `<style>@page{margin:18mm} body{font-family:-apple-system,Segoe UI,Arial,sans-serif;color:#1a1a1a} a{color:#2563eb;text-decoration:none}</style></head>` +
    `<body>${body}</body></html>`
  )
  w.document.close()
  w.focus()
  setTimeout(() => { try { w.print() } catch {} }, 400)
}

// Copy to clipboard — rich HTML + plain text (kept as an option)
export async function copyBrief(o: BriefOpts): Promise<void> {
  const plain = briefPlainText(o)
  const html = briefHtmlBody(o)
  try {
    if (typeof ClipboardItem !== "undefined" && navigator.clipboard?.write) {
      await navigator.clipboard.write([new ClipboardItem({
        "text/html": new Blob([html], { type: "text/html" }),
        "text/plain": new Blob([plain], { type: "text/plain" }),
      })])
    } else {
      await navigator.clipboard.writeText(plain)
    }
  } catch {
    await navigator.clipboard.writeText(plain)
  }
}
